apiVersion: v2
name: story-services
description: A Helm chart for the Story Request and AI Story Creation services with OpenTelemetry sidecars
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: mysql
    version: 13.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: kafka
    version: 32.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled