receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"   # listen on all interfaces
      http:
        endpoint: "0.0.0.0:4318"   # listen on all interfaces

processors:
  batch:

exporters:

  # debug exporter.
  debug:

  # Export to Jaeger through OTLP protocol
  otlphttp/jaeger:
    endpoint: "http://observability-jaeger-collector.observability.svc.cluster.local:4318"
    tls:
      insecure: true

#
#  # Expose metrics to prometheus
#  prometheus:
#    endpoint: "0.0.0.0:8889"
#

  # Logs
  loki:
    endpoint: "http://observability-loki-gateway.observability.svc.cluster.local/loki/api/v1/push"

service:
  pipelines:

    # Traces pipeline goes to Jaeger
    traces:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ otlphttp/jaeger, debug ]

    # Metrics pipeline, for now just export to logging.
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ]

    # Logs pipeline
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ loki ]