apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-story-creation-service.fullname" . }}
  labels:
    {{- include "ai-story-creation-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ai-story-creation-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ai-story-creation-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "ai-story-creation-service.serviceAccountName" . }}

      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
        - name: wait-for-kafka
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              HOST={{ .Release.Name }}-{{ .Values.kafka.host }}
              PORT={{ .Values.kafka.port | default 9092 }}
              echo "⏳ Waiting for Kafka at $HOST:$PORT …"
              
              # keep looping until the port is open
              while ! nc -z -w5 "$HOST" "$PORT"; do
              echo "  … still unreachable, retrying in 2 s"
              sleep 2
              done
              
              echo "✅ Kafka is reachable"

        - name: wait-for-story-request-service
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              HOST={{ .Release.Name }}-{{ .Values.storyRequest.host }}
              PORT={{ .Values.storyRequest.port | default 8080 }}
              echo "⏳ Waiting for story-request at $HOST:$PORT …"
              
              # keep looping until the port is open
              while ! nc -z -w5 "$HOST" "$PORT"; do
                echo "  … still unreachable, retrying in 2 s"
                sleep 2
              done
              
              echo "✅ story-request-service is reachable"

      containers:
        - name: {{ .Chart.Name }}

          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          env:

            - name: STORY_SERVICE_URL
              value: {{ .Release.Name }}-{{ .Values.storyRequest.host }}:{{ .Values.storyRequest.port | default 8080 }}

            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Release.Name }}-{{ .Values.kafka.host }}:{{ .Values.kafka.port | default 9092 }}

            {{- if .Values.env }}
            - name: LLM_PROVIDER
              value: {{ .Values.env.llmProvider.selected }}

            {{- if .Values.env.llmProvider.ollama }}
            - name: OLLAMA_API_URL
              value: {{ .Values.env.llmProvider.ollama.apiUrl }}

            - name: OLLAMA_MODEL
              value: {{ .Values.env.llmProvider.ollama.model }}
            {{- end }}

            - name: KAFKA_TOPIC
              value: {{ .Values.env.kafka.topic }} # TODO This should not be optional, need to ensure its present.

            # If there's an existing secret, read it. Otherwise, read from Values.yaml.
            - name: OPENAI_API_KEY
              {{- if .Values.env.llmProvider.openai.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.llmProvider.openai.existingSecret }}
                  key: api-key
              {{- else }}
              value: {{ .Values.env.llmProvider.openai.apiKey | quote }}
              {{- end }}
            {{- end }}

          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
