# --------------------------------------------------------------------
# observability-suite/values.yaml
# --------------------------------------------------------------------

###############################################################################
# GRAFANA # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
###############################################################################
grafana:

  # TODO: Handle secrets.
  adminUser: Fedderico
  adminPassword: mycustompass

  persistence:
    enabled: true
    size: 10Gi

  service:
    type: ClusterIP
    port: 80

  # Expose UI
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.feddericovonwernich.com
    paths:
      - /

  # Turn the watcher on, this will watch for ConfigMaps that register data sources.
  sidecar:
    datasources:
      enabled: true

###############################################################################
# MINIO # https://raw.githubusercontent.com/bitnami/charts/main/bitnami/minio/values.yaml
###############################################################################
common-minio:
  enabled: true
  auth:
    # TODO: Handle secrets.
    rootUser: "minio"
    rootPassword: "supersecret"
  provisioning:
    enabled: true
    buckets:
      - name: loki-chunks
      - name: loki-ruler
      - name: loki-admin
      - name: tempo-traces
  persistence:
    enabled: true
    size: 20Gi
    storageClass: standard

###############################################################################
# KUBE-PROMETHEUS-STACK # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
###############################################################################
kube-prometheus-stack:

  grafana:
    # Avoid a duplicate Grafana
    enabled: false

  prometheus:

    prometheusSpec:
      retention: 15d
      retentionSize: 30GiB
      # Pick up *all* ServiceMonitors, PodMonitor and Rules from the cluster.
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.feddericovonwernich.com
      # Paths must match the routePrefix (default “/”).
      paths:
        - /
      pathType: Prefix

###############################################################################
# LOKI # https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
###############################################################################
loki:
  deploymentMode: SingleBinary

  singleBinary:
    replicas: 1

  loki:
    commonConfig:
      replication_factor: 1
      path_prefix: /var/loki

    # Disable auth for now
    structuredConfig:
      auth_enabled: false

    storage:
      type: s3
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      s3:
        endpoint: http://{{ .Release.Name }}-common-minio:9000
        insecure: true
        # TODO: Handle secrets.
        accessKeyId: minio
        secretAccessKey: supersecret
        s3ForcePathStyle: true

    schemaConfig:
      configs:
        - from: "2025-07-07"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storageConfig:
      boltdb_shipper:
        shared_store: s3
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 24h

  read: { replicas: 0 }
  write: { replicas: 0 }
  backend: { replicas: 0 }

  # Disable auth for now
  gateway:
    basicAuth:
      enabled: false

##################################################################################
# TEMPO # https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml
##################################################################################

tempo-distributed:

  overrides:
    defaults:
      metrics_generator:
        processors: [service-graphs, span-metrics, local-blocks]

  storage:
    trace:
      backend: s3
      s3:
        # TODO: Handle secrets.
        access_key: "minio"
        secret_key: "supersecret"
        bucket: tempo-traces
        endpoint: "{{ .Release.Name }}-common-minio:9000"
        insecure: true

  traces:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true

  distributor:
    replicaCount: 1

  ingester:
    replicaCount: 1
    wal:
      enabled: true
    lifecycler:
      ring:
        replication_factor: 1
    persistence:
      enabled: true
      storageClass: standard
      accessModes:
        - ReadWriteOnce
      size: 10Gi

  querier:
    replicaCount: 1

  queryFrontend:
    query:
      enabled: true
      replicaCount: 1

  compactor:
    enabled: true
    replicaCount: 1

  memcached:
    enabled: false

  metricsGenerator:
    enabled: true
    replicaCount: 1
    lifecycler:
      ring:
        replication_factor: 1
