global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'otel-collector'
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'jaeger'
    metrics_path: /metrics
    static_configs:
      - targets: ['jaeger:8888']

  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'loki'
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'grafana'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'grafana:3000' ]