apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "story-services.fullname" . }}-story-worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "story-services.fullname" . }}-story-worker
  template:
    metadata:
      labels:
        app: {{ include "story-services.fullname" . }}-story-worker
    spec:
      volumes:
          - name: otel-config
            configMap:
              name: {{ include "story-services.fullname" . }}-otel-config
      initContainers:
          - name: wait-for-kafka
            image: busybox:latest
            command:
              - sh
              - -c
              - |
{{ tpl .Values.waitForKafkaScript . | nindent 17 }}

          - name: wait-for-story-request
            image: busybox:latest
            command:
              - sh
              - -c
              - |
                HOST={{ include "story-services.fullname" . }}-story-request
                PORT={{ .Values.service.storyRequest.port }}
                echo "⏳ Waiting for story-request at $HOST:$PORT …"
                
                # keep looping until the port is open
                while ! nc -z -w5 "$HOST" "$PORT"; do
                  echo "  … still unreachable, retrying in 2 s"
                  sleep 2
                done
                
                echo "✅ story-request is reachable"

      containers:
          - name: story-worker
            image: {{ .Values.image.storyWorker.repository }}:{{ .Values.image.storyWorker.tag }}
            imagePullPolicy: {{ .Values.image.storyWorker.pullPolicy }}
            env:
              - name: LLM_PROVIDER
                value: {{ .Values.env.storyWorker.llmProvider }}
              - name: STORY_SERVICE_URL
                value: {{ include "story-services.fullname" . }}-story-request:{{ .Values.service.storyRequest.port }}
              - name: OPENAI_API_KEY
                value: {{ .Values.env.storyWorker.openAiApiKey }}
              - name: KAFKA_TOPIC
                value: {{ .Values.env.storyWorker.kafkaTopic }}
              - name: KAFKA_BOOTSTRAP_SERVERS
                value: {{ include "story-services.releaseName" . }}-kafka:{{ .Values.kafka.port | default 9092 }}

            resources:
{{ toYaml .Values.resources | indent 14 }}
{{- include "otel-sidecar" . | indent 10 }}