apiVersion: v1
kind: Service
metadata:
  name: {{ include "story-services.fullname" . }}-story-request
spec:
  type: ClusterIP
  selector:
    app: {{ include "story-services.fullname" . }}-story-request
  ports:
    - port: {{ .Values.service.storyRequest.port }}
      targetPort: {{ .Values.service.storyRequest.port }}
      name: http