# ──────────────────────────────────────────────────────────────────
# This configuration will be used when deploying on a kubernetes cluster, most of the configs will be handled
#  when deploying.
# ──────────────────────────────────────────────────────────────────
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true