# ──────────────────────────────────────────────────────────────────
# Used to configure the app within a docker-compose environment environment.
# ──────────────────────────────────────────────────────────────────
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/blog_db
    username: root
    password: rootpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: kafka:9092
