apiVersion: v1
kind: Service
metadata:
  name: {{ include "story-services.fullname" . }}-story-worker
spec:
  type: ClusterIP
  selector:
    app: {{ include "story-services.fullname" . }}-story-worker
  ports:
    - port: {{ .Values.service.storyWorker.port }}
      targetPort: {{ .Values.service.storyWorker.port }}
      name: http