apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "story-services.fullname" . }}-story-request
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "story-services.fullname" . }}-story-request
  template:
    metadata:
      labels:
        app: {{ include "story-services.fullname" . }}-story-request
    spec:
      volumes:
          - name: otel-config
            configMap:
              name: {{ include "story-services.fullname" . }}-otel-config
      initContainers:
          - name: wait-for-mysql
            image: busybox:latest
            command:
              - sh
              - -c
              - |
{{ tpl .Values.waitForMysqlScript . | nindent 17 }}

          - name: wait-for-kafka
            image: busybox:latest
            command:
              - sh
              - -c
              - |
{{ tpl .Values.waitForKafkaScript . | nindent 17 }}

      containers:
          - name: story-request-service
            image: {{ .Values.image.storyRequest.repository }}:{{ .Values.image.storyRequest.tag }}
            imagePullPolicy: {{ .Values.image.storyRequest.pullPolicy }}
            ports:
              - containerPort: {{ .Values.service.storyRequest.port }}
            env:
              - name: SPRING_DATASOURCE_URL
                value: jdbc:mysql://{{ include "story-services.releaseName" . }}-mysql:{{ .Values.mysql.port }}/{{ .Values.mysql.auth.database }}
              - name: SPRING_DATASOURCE_USERNAME
                value: {{ .Values.mysql.auth.username }}
              - name: SPRING_DATASOURCE_PASSWORD
                value: {{ .Values.mysql.auth.password }}
              - name: SPRING_PROFILES_ACTIVE
                value: kube
              - name: JAVA_OPTS
                value: {{ .Values.env.storyRequest.javaOps }}
              - name: KAFKA_BOOTSTRAP_SERVERS
                value: {{ include "story-services.releaseName" . }}-kafka:{{ .Values.kafka.port | default 9092 }}

              # TODO Well, these should not be hardcoded here.
              - name: OTEL_ENABLED
                value: "true"
              - name: OTEL_SERVICE_NAME
                value: story-request-service
              - name: OTEL_RESOURCE_ATTRIBUTES
                value: service.version=1.0,deployment.environment=docker
              - name: OTEL_TRACES_EXPORTER
                value: otlp
              - name: OTEL_METRICS_EXPORTER
                value: otlp
              - name: OTEL_LOGS_EXPORTER
                value: otlp
              - name: OTEL_EXPORTER_OTLP_ENDPOINT
                value: http://localhost:4318
              - name: OTEL_EXPORTER_OTLP_PROTOCOL
                value: http/protobuf
              - name: OTEL_PROPAGATORS
                value: tracecontext,baggage
            resources:
{{ toYaml .Values.resources | indent 14 }}
{{- include "otel-sidecar" . | indent 10 }}