apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability-suite.fullname" . }}-datasources
  labels:
    # Label must match the side-car settings
    grafana_datasource: "1"
    {{- include "observability-suite.labels" . | nindent 4 }}
data:

  datasources.yaml: |
    apiVersion: 1
    datasources:
    
      - name: Prometheus
        uid: prometheus
        type: prometheus
        url: http://{{ .Release.Name }}-kube-prometh-prometheus:9090
        access: proxy
        isDefault: true
        editable: false

      - name: Jaeger
        uid: jaeger
        type: jaeger
        access: proxy
        url: http://{{ .Release.Name }}-jaeger-query:16686
        editable: false

      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://{{ .Release.Name }}-loki-gateway
        editable: false
